<?php

namespace RpWebDevelopment\LaravelUgcTranslate\Traits;

trait DeepLLanguageCodes
{
    protected array $targetLanguageCodes = [
        'ar_AA' => 'ar',
        'bg_BG' => 'bg',
        'cs_CZ' => 'cs',
        'da_DK' => 'da',
        'de_DE' => 'de',
        'el_GR' => 'el',
        'en_AU' => 'en',
        'en_BE' => 'en',
        'en_GB' => 'EN-GB',
        'en_US' => 'en-US',
        'en_ZA' => 'en',
        'es_ES' => 'es',
        'et_ET' => 'et',
        'fi_FI' => 'fi',
        'fr_BE' => 'fr',
        'fr_CA' => 'fr',
        'fr_CH' => 'fr',
        'fr_FR' => 'fr',
        'hu_HU' => 'hu',
        'id_ID' => 'id',
        'it_CH' => 'it',
        'it_IT' => 'it',
        'ja_JP' => 'ja',
        'lt_LT' => 'lt',
        'lv_LV' => 'lv',
        'nl_NL' => 'nl',
        'nl_BE' => 'nl',
        'pl_PL' => 'pl',
        'pt' => 'pt',
        'pt_BR' => 'pt-BR',
        'pt_PT' => 'pt-PT',
        'ro_RO' => 'ro',
        'ru_RU' => 'ru',
        'sk_SK' => 'sk',
        'sl_SL' => 'sl',
        'sv_SE' => 'sv',
        'tr_TR' => 'tr',
        'uk_UA' => 'uk',
        'zh_CN' => 'zh',
    ];

    protected array $sourceLanguageCodes = [
        'ar_AA' => 'ar',
        'bg_BG' => 'bg',
        'cs_CZ' => 'cs',
        'da_DK' => 'da',
        'de_DE' => 'de',
        'el_GR' => 'el',
        'en_AU' => 'en',
        'en_BE' => 'en',
        'en_GB' => 'en',
        'en_US' => 'en',
        'en_ZA' => 'en',
        'es_ES' => 'es',
        'et_ET' => 'et',
        'fi_FI' => 'fi',
        'fr_BE' => 'fr',
        'fr_CA' => 'fr',
        'fr_CH' => 'fr',
        'fr_FR' => 'fr',
        'hu_HU' => 'hu',
        'id_ID' => 'id',
        'it_CH' => 'it',
        'it_IT' => 'it',
        'ja_JP' => 'ja',
        'lt_LT' => 'lt',
        'lv_LV' => 'lv',
        'nl_NL' => 'nl',
        'nl_BE' => 'nl',
        'pl_PL' => 'pl',
        'pt_BR' => 'pt',
        'pt_PT' => 'pt',
        'ro_RO' => 'ro',
        'ru_RU' => 'ru',
        'sk_SK' => 'sk',
        'sl_SL' => 'sl',
        'sv_SE' => 'sv',
        'tr_TR' => 'tr',
        'uk_UA' => 'uk',
        'zh_CN' => 'zh',
    ];
}
